### PR TITLE
Methods to erase bit in partial truth table

### PR DESCRIPTION
**Pull request by lee30sonia**
This PR implements methods to erase a bit in a partial truth table.
It also fixes some small issues and completes the documentation for `partial_truth_table`.

### CODE REVIEW

**Review by msoeken — APPROVED** [review]
LGTM, thanks!

**Comment by lee30sonia** [comment]
I don't have write access to kitty. Could you merge it if it's okay?

**Comment by msoeken** [comment]
Thanks @hriener for merging. @lee30sonia, you have access now as well.

**Comment by lee30sonia** [comment]
Thanks!

**Pull request merged**
